CREATE TABLE IF NOT EXISTS leads (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    vk VARCHAR(255),
    telegram VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);